version: '3'

services:
  web:
    build: '.'
    environment: 
      - "BULENAT_USER=bulenat"
      - "BULENAT_PASS=bulenat1234"
      - "BULENAT_DB=gobulenat"
      - "BULENAT_PORT=5432"
      - "BULENAT_HOST=pgsql"
  pgsql:
    image: 'postgres:11'
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=bulenat"
      - "POSTGRES_PASSWORD=bulenat1234"
      - "POSTGRES_DB=bulenat"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  data: