version: '3'

services:
  gobulenat:
    build: '../.'
    environment: 
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=bulenat1234"
      - "DATABASE_DB=gobulenat"
      - "DATABASE_PORT=5432"
      - "DATABASE_HOST=pgsql"
      - "DATABASE_SSL=disable"
    depends_on: 
      - pgsql

  pgsql:
    image: 'postgres:11'
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=bulenat1234"
      - "POSTGRES_DB=gobulenat"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  data: